version: "2.1"

services:
  crossbar-service:
    image: crossbario/crossbar
    ports:
      - "8080:8080"
    volumes:
      - ./client:/node/web
      - ./crossbar-service/config.json:/node/.crossbar/config.json
#    networks:
#      - internal
#      - public
    network_mode: host
    command: [--logformat, syslogd, --loglevel, info]
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:8080/ws"]



  user-service:
    build:
      dockerfile: Dockerfile-common
      context: ./javascript
      args:
        SERVICE_SOURCE_SUBDIR: user-service
    image: samson84/schnapsen-user-service
    depends_on:
      crossbar-service:
        condition: service_healthy
    network_mode: host
#    networks:
#      - internal

  table-service:
    build:
      dockerfile: Dockerfile-common
      context: ./javascript
      args:
        SERVICE_SOURCE_SUBDIR: table-service
    image: samson84/schnapsen-table-service
    depends_on:
      crossbar-service:
        condition: service_healthy
    network_mode: host
#    networks:
#      - internal

#networks:
#  internal:
#    driver: bridge
#  public:
#    driver: bridge
