version: "2"

services:
  crossbar-service:
    image: crossbario/crossbar
    ports:
      - "8080:8080"
    volumes:
      - ./client:/node/web
      - ./crossbar-service/config.json:/node/.crossbar/config.json
    networks:
      - internal
      - public
    command: [--logformat, syslogd, --loglevel, info]


  user-service:
    image: samson84/schnapsen-user-service
    depends_on:
      - crossbar-service
    networks:
      - internal

  table-service:
    image: samson84/schnapsen-table-service
    depends_on:
      - crossbar-service
    networks:
      - internal

networks:
  internal:
  public:
